In [1]:
'''
【课程2.14】  数值计算和统计基础

常用数学、统计方法
 
'''

'\n【课程2.14】  数值计算和统计基础\n\n常用数学、统计方法\n \n'

In [2]:
# 基本参数：axis、skipna

import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':[4,5,3,np.nan,2],
                  'key2':[1,2,np.nan,4,5],
                  'key3':[1,2,3,'j','k']},
                  index=['a','b','c','d','e'])
print(df)
print(df['key1'].dtype)
print(df['key2'].dtype)
print(df['key3'].dtype)
print('-----------------------------------')

m1 = df.mean(axis=0)                    #默认按照列统计
print(m1,type(m1))
print(df['key2'].mean())
# np.nan ：空值
# .mean()计算均值
# 只统计数字列
# 可以通过索引单独统计一列
print('-----------------------------------')

m2 = df.mean(axis=1)
print(m2,type(m2))
# axis参数：默认为0，以列来计算，axis=1，以行来计算，这里就按照行来汇总了
print('-----------------------------------')

m3 = df.mean(skipna=False)
print(m3,type(m3))
# skipna参数：是否忽略NaN，默认True，如False，有NaN的列统计结果仍未NaN

   key1  key2 key3
a   4.0   1.0    1
b   5.0   2.0    2
c   3.0   NaN    3
d   NaN   4.0    j
e   2.0   5.0    k
float64
float64
object
-----------------------------------
key1    3.5
key2    3.0
dtype: float64 <class 'pandas.core.series.Series'>
3.0
-----------------------------------
a    2.5
b    3.5
c    3.0
d    4.0
e    3.5
dtype: float64 <class 'pandas.core.series.Series'>
-----------------------------------
key1   NaN
key2   NaN
dtype: float64 <class 'pandas.core.series.Series'>

In [3]:
# 主要数学计算方法，可用于Series和DataFrame（1）

df = pd.DataFrame({'key1':np.arange(10),
                  'key2':np.random.rand(10)*10})
print(df)
print('----------------------------------')

print(df.count(),'\n')                # 统计非Na值的数量
print(df.max(),df.min(),'\n')
print(df.sum(),'\n')
print(df.quantile(0.8),'\n')          # quantile统计分位数，参数q确定位置
print(df.mean(),'\n')
print(df.median(),'\n')              # 求算数中位数，50%分位数
print(df.std(),df.var(),'\n')        # 计算标准差，方差
print(df.skew(),'\n')                # 样本的偏度
print(df.kurt(),'\n')                # 样本的峰度

   key1      key2
0     0  8.856200
1     1  8.050655
2     2  3.378470
3     3  5.263900
4     4  8.682772
5     5  7.366653
6     6  4.815735
7     7  3.735089
8     8  4.992235
9     9  3.509870
----------------------------------
key1    10
key2    10
dtype: int64

key1    9.0000
key2    8.8562
dtype: float64 key1    0.00000
key2    3.37847
dtype: float64

key1    45.000000
key2    58.651579
dtype: float64

key1    7.200000
key2    8.177078
Name: 0.8, dtype: float64

key1    4.500000
key2    5.865158
dtype: float64

key1    4.500000
key2    5.128067
dtype: float64

key1    3.027650
key2    2.170744
dtype: float64 key1    9.166667
key2    4.712128
dtype: float64

key1    0.000000
key2    0.309671
dtype: float64

key1   -1.200000
key2   -1.759246
dtype: float64

In [4]:
# 主要数学计算方法，可用于Series和DataFrame（2）

df = pd.DataFrame({'key1':np.arange(10),
                  'key2':np.random.rand(10)*10})
print(df)
df['key1_s'] = df['key1'].cumsum()
df['key2_s'] = df['key2'].cumsum()  
# cumsum 样本的累积和
print(df,'\n')

df['key1_p'] = df['key1'].cumprod()
df['key2_p'] = df['key2'].cumprod()
# cumprod 样本的累计积
print(df,'\n')

print(df.cummax(),'\n',df.cummin())
# cummax,cummin分别求累计最大值，累计最小值

   key1      key2
0     0  2.761366
1     1  5.697302
2     2  2.150565
3     3  1.758667
4     4  9.437381
5     5  9.412890
6     6  4.990319
7     7  8.037900
8     8  8.731995
9     9  5.487461
   key1      key2  key1_s     key2_s
0     0  2.761366       0   2.761366
1     1  5.697302       1   8.458668
2     2  2.150565       3  10.609232
3     3  1.758667       6  12.367899
4     4  9.437381      10  21.805280
5     5  9.412890      15  31.218170
6     6  4.990319      21  36.208489
7     7  8.037900      28  44.246389
8     8  8.731995      36  52.978385
9     9  5.487461      45  58.465845

   key1      key2  key1_s     key2_s  key1_p        key2_p
0     0  2.761366       0   2.761366       0  2.761366e+00
1     1  5.697302       1   8.458668       0  1.573233e+01
2     2  2.150565       3  10.609232       0  3.383340e+01
3     3  1.758667       6  12.367899       0  5.950167e+01
4     4  9.437381      10  21.805280       0  5.615400e+02
5     5  9.412890      15  31.218170       0  5.285714e+03
6     6  4.990319      21  36.208489       0  2.637740e+04
7     7  8.037900      28  44.246389       0  2.120189e+05
8     8  8.731995      36  52.978385       0  1.851348e+06
9     9  5.487461      45  58.465845       0  1.015920e+07

   key1      key2  key1_s     key2_s  key1_p        key2_p
0   0.0  2.761366     0.0   2.761366     0.0  2.761366e+00
1   1.0  5.697302     1.0   8.458668     0.0  1.573233e+01
2   2.0  5.697302     3.0  10.609232     0.0  3.383340e+01
3   3.0  5.697302     6.0  12.367899     0.0  5.950167e+01
4   4.0  9.437381    10.0  21.805280     0.0  5.615400e+02
5   5.0  9.437381    15.0  31.218170     0.0  5.285714e+03
6   6.0  9.437381    21.0  36.208489     0.0  2.637740e+04
7   7.0  9.437381    28.0  44.246389     0.0  2.120189e+05
8   8.0  9.437381    36.0  52.978385     0.0  1.851348e+06
9   9.0  9.437381    45.0  58.465845     0.0  1.015920e+07
    key1      key2  key1_s    key2_s  key1_p    key2_p
0   0.0  2.761366     0.0  2.761366     0.0  2.761366
1   0.0  2.761366     0.0  2.761366     0.0  2.761366
2   0.0  2.150565     0.0  2.761366     0.0  2.761366
3   0.0  1.758667     0.0  2.761366     0.0  2.761366
4   0.0  1.758667     0.0  2.761366     0.0  2.761366
5   0.0  1.758667     0.0  2.761366     0.0  2.761366
6   0.0  1.758667     0.0  2.761366     0.0  2.761366
7   0.0  1.758667     0.0  2.761366     0.0  2.761366
8   0.0  1.758667     0.0  2.761366     0.0  2.761366
9   0.0  1.758667     0.0  2.761366     0.0  2.761366

In [5]:
# 唯一值：.unique()

s = pd.Series(list('asdfghjklsdjgalt'))
sq = s.unique()
print(s)
print(sq,type(sq))
print(pd.Series(sq))
# 得到一个唯一值数组
# 通过pd.Series重新变成新的Series

sq.sort()
print(sq)
# 重新排序

0     a
1     s
2     d
3     f
4     g
5     h
6     j
7     k
8     l
9     s
10    d
11    j
12    g
13    a
14    l
15    t
dtype: object
['a' 's' 'd' 'f' 'g' 'h' 'j' 'k' 'l' 't'] <class 'numpy.ndarray'>
0    a
1    s
2    d
3    f
4    g
5    h
6    j
7    k
8    l
9    t
dtype: object
['a' 'd' 'f' 'g' 'h' 'j' 'k' 'l' 's' 't']

In [6]:
# 值计数：.value_counts()

sc = s.value_counts(sort=False)   # 也可以这样写：pd.value_counts(sc, sort = False)
print(sc)
# 得到一个新的Series，计算出不同值出现的频率
# sort参数：排序，默认为True

j    2
g    2
h    1
t    1
s    2
k    1
l    2
d    2
f    1
a    2
dtype: int64

In [7]:
# 成员资格：.isin()

s = pd.Series(np.arange(10,15))
df = pd.DataFrame({'key1':list('qwertyweqp'),
                  'key2':np.arange(5,15)})
print(s)
print(df)
print('---------------------')
 
print(s.isin([5,14]))                   # 分别判断s中的元素是否在[5,14]范围内
print(df.isin(['q',12,'sad']))          # 分别判断df中的每个元素是否在给定区间范围内
# 用[]表示
# 得到一个布尔值的Series或者Dataframe

0    10
1    11
2    12
3    13
4    14
dtype: int32
  key1  key2
0    q     5
1    w     6
2    e     7
3    r     8
4    t     9
5    y    10
6    w    11
7    e    12
8    q    13
9    p    14
---------------------
0    False
1    False
2    False
3    False
4     True
dtype: bool
    key1   key2
0   True  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False   True
8   True  False
9  False  False

In [8]:
'''
【课程2.15】  文本数据

Pandas针对字符串配备的一套方法，使其易于对数组的每个元素进行操作
 
'''

'\n【课程2.15】  文本数据\n\nPandas针对字符串配备的一套方法，使其易于对数组的每个元素进行操作\n \n'

In [9]:
# 通过str访问，且自动排除丢失/ NA值

s = pd.Series(['A','b','hello','C',45,'123',np.nan])
df = pd.DataFrame({'key1':list('abcdefg'),
                  'key2':['haha',np.nan,'78','pom','era',36,'MP']})
print(s)
print(df)
print('--------------------------')

print(s.str.count('b'))
print(df['key2'].str.upper())
print('--------------------------')
# 直接通过.str调用字符串方法
# 可以对Series、Dataframe使用
# 自动过滤NaN值

df.columns = df.columns.str.upper()
print(df)
print(df.columns)

0        A
1        b
2    hello
3        C
4       45
5      123
6      NaN
dtype: object
  key1  key2
0    a  haha
1    b   NaN
2    c    78
3    d   pom
4    e   era
5    f    36
6    g    MP
--------------------------
0    0.0
1    1.0
2    0.0
3    0.0
4    NaN
5    0.0
6    NaN
dtype: float64
0    HAHA
1     NaN
2      78
3     POM
4     ERA
5     NaN
6      MP
Name: key2, dtype: object
--------------------------
  KEY1  KEY2
0    a  haha
1    b   NaN
2    c    78
3    d   pom
4    e   era
5    f    36
6    g    MP
Index(['KEY1', 'KEY2'], dtype='object')

In [10]:
# 字符串常用方法（1） - lower，upper，len，startswith，endswith

s = pd.Series(['A','b','bbhello','123',np.nan])

print(s.str.lower(),'→ lower小写\n')
print(s.str.upper(),'→ upper大写\n')
print(s.str.len(),'→ len字符长度\n')
print(s.str.startswith('b'),'→ 判断起始是否为a\n')
print(s.str.endswith('3'),'→ 判断结束是否为3\n')

0          a
1          b
2    bbhello
3        123
4        NaN
dtype: object → lower小写

0          A
1          B
2    BBHELLO
3        123
4        NaN
dtype: object → upper大写

0    1.0
1    1.0
2    7.0
3    3.0
4    NaN
dtype: float64 → len字符长度

0    False
1     True
2     True
3    False
4      NaN
dtype: object → 判断起始是否为a

0    False
1    False
2    False
3     True
4      NaN
dtype: object → 判断结束是否为3

In [11]:
# 字符串常用方法（2） - strip

s = pd.Series(['Bill    ','    Liberty','         wave ','pale '])
df = pd.DataFrame(np.random.randn(3,2),
                  index=range(3),
                 columns = ['ColumnA','ColumnB'] )
print(s)
print(df)
print('-------------------------------')

print(s.str.strip())                # 去除字符串中的空格
print(s.str.lstrip())               # 去除字符串中的左空格
print(s.str.rstrip())               # 去除字符串中的右空格
print('--------------------------------')

df.columns = df.columns.str.strip()
print(df)

0          Bill
1           Liberty
2             wave
3             pale
dtype: object
    ColumnA   ColumnB
0 -0.879506 -0.602513
1  0.146579 -1.428597
2 -1.703196 -0.887671
-------------------------------
0       Bill
1    Liberty
2       wave
3       pale
dtype: object
0    Bill
1     Liberty
2       wave
3       pale
dtype: object
0             Bill
1          Liberty
2             wave
3             pale
dtype: object
--------------------------------
    ColumnA   ColumnB
0 -0.879506 -0.602513
1  0.146579 -1.428597
2 -1.703196 -0.887671

In [12]:
# 字符串常用方法（3） - replace

df = pd.DataFrame(np.random.randn(3, 2), 
                  columns=[' Column A ', ' Column B '],
                  index=range(3))
df.columns = df.columns.str.replace(' ','-')
print(df)
df.columns = df.columns.str.replace('-','ha',n=2)
print(df)

   -Column-A-  -Column-B-
0   -1.025479    0.529690
1   -1.215244   -0.836545
2   -0.360322   -0.965025
   haColumnhaA-  haColumnhaB-
0     -1.025479      0.529690
1     -1.215244     -0.836545
2     -0.360322     -0.965025

In [13]:
# 字符串常用方法（4） - split、rsplit

s = pd.Series(['a,b,c','1,2,3',['a,,,c'],np.nan])
print(s)
print(s.str.split(','))
# 类似字符串的split
print('-----------------------------')

print(s.str.split(',')[0])
print('-----------------------------')
# 直接索引得到一个list

print(s.str.split(',')[0])
print(s.str.split(',').str.get(1))
# 可以使用get或[]符号访问拆分列表中的元素
print('----------------------------')

print(s.str.split(',',expand=True))
print(s.str.split(',',expand=True,n=1))
print(s.str.rsplit(',',expand=True,n=1))
# 可以使用expand可以轻松扩展此操作以返回DataFrame
# n参数限制分割数
# rsplit类似于split，反向工作，即从字符串的末尾到字符串的开头
print('------------------------------')
df = pd.DataFrame({'key1':['a,b,c','1,2,3',[':,., ']],
                  'key2':['a-b-c','1-2-3',[':-.- ']]})
print(df)
print(df['key2'].str.split('-'))
# Dataframe使用split

0      a,b,c
1      1,2,3
2    [a,,,c]
3        NaN
dtype: object
0    [a, b, c]
1    [1, 2, 3]
2          NaN
3          NaN
dtype: object
-----------------------------
['a', 'b', 'c']
-----------------------------
['a', 'b', 'c']
0      b
1      2
2    NaN
3    NaN
dtype: object
----------------------------
     0    1    2
0    a    b    c
1    1    2    3
2  NaN  NaN  NaN
3  NaN  NaN  NaN
     0    1
0    a  b,c
1    1  2,3
2  NaN  NaN
3  NaN  NaN
     0    1
0  a,b    c
1  1,2    3
2  NaN  NaN
3  NaN  NaN
------------------------------
      key1     key2
0    a,b,c    a-b-c
1    1,2,3    1-2-3
2  [:,., ]  [:-.- ]
0    [a, b, c]
1    [1, 2, 3]
2          NaN
Name: key2, dtype: object

In [14]:
# 字符串索引

s = pd.Series(['A','b','C','bbhello','123',np.nan,'hj'])
df = pd.DataFrame({'key1':list('abcdef'),
                  'key2':['hee','fv','w','hija','123',np.nan]})

print(s[0])      # 注意二者区别
print(s.str[0])  # 取第一个字符串
print(s.str[:2])  # 取前两个字符串
print(df['key2'].str[0]) 
# str之后和字符串本身索引方式相同

A
0      A
1      b
2      C
3      b
4      1
5    NaN
6      h
dtype: object
0      A
1      b
2      C
3     bb
4     12
5    NaN
6     hj
dtype: object
0      h
1      f
2      w
3      h
4      1
5    NaN
Name: key2, dtype: object

In [15]:
'''
【课程2.16】  合并 merge、join

Pandas具有全功能的，高性能内存中连接操作，与SQL等关系数据库非常相似

pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None,
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False)
 
'''

"\n【课程2.16】  合并 merge、join\n\nPandas具有全功能的，高性能内存中连接操作，与SQL等关系数据库非常相似\n\npd.merge(left, right, how='inner', on=None, left_on=None, right_on=None,\n         left_index=False, right_index=False, sort=True,\n         suffixes=('_x', '_y'), copy=True, indicator=False)\n \n"

In [16]:
# merge合并 → 类似excel的vlookup

df1 = pd.DataFrame({'key':['K0','K1','K1','K2'],
                   'A':['A0','A1','A2','A3'],
                   'B':['B0','B1','B2','B3']})
df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})
df3 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K1'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})
df4 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                    'key2': ['K0', 'K0', 'K0', 'K0'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})
print(pd.merge(df1,df2,on='key'))
print('----------------------------')
# left：第一个df
# right：第二个df
# on：参考键

print(pd.merge(df3,df4,on=['key1','key2']))
# 多个链接键

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K1  A2  B2  C1  D1
3  K2  A3  B3  C2  D2
----------------------------
  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [17]:
# 参数how → 合并方式

print(df3,'\n',df4)
print('---------------------------------------------')

print(pd.merge(df3,df4,on=['key1','key2'], how = 'inner'))
# inner：默认，取交集
print('----------------------------------------------')

print(pd.merge(df3,df4,on=['key1','key2'],how = 'outer'))
# outer：取并集，数据缺失范围NaN
print('----------------------------------------------')

print(pd.merge(df3,df4,on=['key1','key2'],how = 'left'))
# left：按照df3为参考合并，数据缺失范围NaN
print('---------------------------------------------')

print(pd.merge(df3,df4,on=['key1','key2'],how = 'right'))
# right：按照df4为参考合并，数据缺失范围NaN

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3
   key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3
---------------------------------------------
  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2
----------------------------------------------
  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3
----------------------------------------------
  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN
---------------------------------------------
  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [18]:
# 参数 left_on, right_on, left_index, right_index → 当键不为一个列时，可以单独设置左键与右键

df1 = pd.DataFrame({'lkey':list('bbacaab'),
                   'data1':range(7)})
df2 = pd.DataFrame({'rkey':list('abd'),
                   'data2':range(3)})
print(df1)
print(df2)
print('--------------------------------------')
print(pd.merge(df1,df2,left_on='lkey',right_on='rkey'))
# df1以‘lkey’为键，df2以‘rkey’为键

print('---------------------------------------')

df1 = pd.DataFrame({'key':list('abcdfeg'),
                   'data1':range(7)})
df2 = pd.DataFrame({'date2':range(100,105)},
                  index = list('abcde'))
print(df1,'\n',df2)
print(pd.merge(df1,df2,left_on='key',right_index=True))
# df1以‘key’为键，df2以index为键
# left_index：为True时，第一个df以index为键，默认False
# right_index：为True时，第二个df以index为键，默认False

# 所以left_on, right_on, left_index, right_index可以相互组合：
# left_on + right_on, left_on + right_index, left_index + right_on, left_index + right_index

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6
  rkey  data2
0    a      0
1    b      1
2    d      2
--------------------------------------
  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0
---------------------------------------
  key  data1
0   a      0
1   b      1
2   c      2
3   d      3
4   f      4
5   e      5
6   g      6
    date2
a    100
b    101
c    102
d    103
e    104
  key  data1  date2
0   a      0    100
1   b      1    101
2   c      2    102
3   d      3    103
5   e      5    104

In [19]:
# 参数 sort

df1 = pd.DataFrame({'key':list('bbacaab'),
                   'data1':[1,3,2,4,5,9,7]})
df2 = pd.DataFrame({'key':list('abd'),
                   'date2':[11,2,33]})
print(df1,'\n',df2)
print('----------------------------------')

print(pd.merge(df1,df2,on='key',how='outer'))
print(pd.merge(df1,df2,on='key',sort=True,how='outer'))
# sort：按照字典顺序通过 连接键 对结果DataFrame进行排序。默认为False，设置为False会大幅提高性能

print('-----------------------------------')
print(pd.merge(df1,df2,on='key',how='outer').sort_values('data1'))
# 也可直接用Dataframe的排序方法：sort_values，sort_index

  key  data1
0   b      1
1   b      3
2   a      2
3   c      4
4   a      5
5   a      9
6   b      7
   key  date2
0   a     11
1   b      2
2   d     33
----------------------------------
  key  data1  date2
0   b    1.0    2.0
1   b    3.0    2.0
2   b    7.0    2.0
3   a    2.0   11.0
4   a    5.0   11.0
5   a    9.0   11.0
6   c    4.0    NaN
7   d    NaN   33.0
  key  data1  date2
0   a    2.0   11.0
1   a    5.0   11.0
2   a    9.0   11.0
3   b    1.0    2.0
4   b    3.0    2.0
5   b    7.0    2.0
6   c    4.0    NaN
7   d    NaN   33.0
-----------------------------------
  key  data1  date2
0   b    1.0    2.0
3   a    2.0   11.0
1   b    3.0    2.0
6   c    4.0    NaN
4   a    5.0   11.0
2   b    7.0    2.0
5   a    9.0   11.0
7   d    NaN   33.0

In [20]:
# pd.join() → 直接通过索引链接

left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                    index=['K0', 'K1', 'K2'])
right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                     index=['K0', 'K2', 'K3'])
print(left,'\n',right)
print('----------------------------------')

print(left.join(right),'\n')
print(left.join(right,how = 'outer'),'\n')
print(right.join(left,how = 'outer'),'\n')
print(pd.merge(left,right,left_index=True,right_index=True,how = 'outer'))
# 采用join连接时，可转换为pd.merge(),注意参数设置
print('----------------------------------')
df1 = pd.DataFrame({'key':list('bbacaab'),
                   'data1':[1,3,2,4,5,9,7]})
df2 = pd.DataFrame({'key':list('abd'),
                   'date2':[11,2,33]})
print(df1,'\n',df2)
print('----------------------------------')
print(pd.merge(df1,df2,left_index=True,right_index=True,suffixes=('_1','_2')))
print(df1.join(df2['date2']))
# suffixes=('_x', '_y')默认
print('----------------------------------')

left = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'key': ['K0', 'K1', 'K0', 'K1']})
right = pd.DataFrame({'C': ['C0', 'C1'],
                      'D': ['D0', 'D1']},
                     index=['K0', 'K1'])
print(left,'\n',right)
print(left.join(right,on='key'))
# 等价于pd.merge(left, right, left_on='key', right_index=True, how='left', sort=False);
# left的‘key’和right的index
print(pd.merge(left,right,left_on='key',right_index=True,how = 'left'))

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
      C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3
----------------------------------
     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

      C    D    A    B
K0   C0   D0   A0   B0
K1  NaN  NaN   A1   B1
K2   C2   D2   A2   B2
K3   C3   D3  NaN  NaN

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3
----------------------------------
  key  data1
0   b      1
1   b      3
2   a      2
3   c      4
4   a      5
5   a      9
6   b      7
   key  date2
0   a     11
1   b      2
2   d     33
----------------------------------
  key_1  data1 key_2  date2
0     b      1     a     11
1     b      3     b      2
2     a      2     d     33
  key  data1  date2
0   b      1   11.0
1   b      3    2.0
2   a      2   33.0
3   c      4    NaN
4   a      5    NaN
5   a      9    NaN
6   b      7    NaN
----------------------------------
    A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K0
3  A3  B3  K1
      C   D
K0  C0  D0
K1  C1  D1
    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K0  C0  D0
3  A3  B3  K1  C1  D1
    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K0  C0  D0
3  A3  B3  K1  C1  D1

In [21]:
'''
【课程2.17】  连接与修补 concat、combine_first

连接 - 沿轴执行连接操作

pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
          keys=None, levels=None, names=None, verify_integrity=False,
          copy=True)
 
'''

"\n【课程2.17】  连接与修补 concat、combine_first\n\n连接 - 沿轴执行连接操作\n\npd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,\n          keys=None, levels=None, names=None, verify_integrity=False,\n          copy=True)\n \n"

In [22]:
# 连接：concat

s1 = pd.Series([1,2,3])
s2 = pd.Series([2,3,4])
s3 = pd.Series([1,2,3],index = ['a','c','h'])
s4 = pd.Series([2,3,4],index = ['b','e','d'])

# print(s1,'\n',s2)
print(pd.concat([s1,s2]))
print(pd.concat([s3,s4]).sort_index())
# 默认axis=0，行+行
print('-------------------------')
print(s3,'\n',s4)
print(pd.concat([s3,s4],axis=1))
# axis=1,列+列，成为一个Dataframe

0    1
1    2
2    3
0    2
1    3
2    4
dtype: int64
a    1
b    2
c    2
d    4
e    3
h    3
dtype: int64
-------------------------
a    1
c    2
h    3
dtype: int64
 b    2
e    3
d    4
dtype: int64
     0    1
a  1.0  NaN
b  NaN  2.0
c  2.0  NaN
d  NaN  4.0
e  NaN  3.0
h  3.0  NaN

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [23]:
# 连接方式：join，join_axes

s5 = pd.Series([1,2,3],index = ['a','b','c'])
s6 = pd.Series([2,3,4],index = ['b','c','d'])
print(pd.concat([s5,s6], axis= 1))
print(pd.concat([s5,s6], axis= 1, join='inner'))
print(pd.concat([s5,s6], axis= 1, join_axes=[['a','b','d']]))
# join：{'inner'，'outer'}，默认为“outer”。如何处理其他轴上的索引。outer为联合和inner为交集。
# join_axes：指定联合的index

     0    1
a  1.0  NaN
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
   0  1
b  2  2
c  3  3
     0    1
a  1.0  NaN
b  2.0  2.0
d  NaN  4.0

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """

In [24]:
# 覆盖列名

print(s5,'\n',s6)
print('-------------------------------------')
sre = pd.concat([s5,s6],keys=['one','two'])
print(sre,type(sre))
print(sre.index)
# keys：序列，默认值无。使用传递的键作为最外层构建层次索引
print('--------------------------------------')

ser = pd.concat([s5,s6],axis=1,keys=['one','two'])
print(ser,type(ser))

a    1
b    2
c    3
dtype: int64
 b    2
c    3
d    4
dtype: int64
-------------------------------------
one  a    1
     b    2
     c    3
two  b    2
     c    3
     d    4
dtype: int64 <class 'pandas.core.series.Series'>
MultiIndex(levels=[['one', 'two'], ['a', 'b', 'c', 'd']],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 1, 2, 3]])
--------------------------------------
   one  two
a  1.0  NaN
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0 <class 'pandas.core.frame.DataFrame'>

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # This is added back by InteractiveShellApp.init_path()

In [25]:
# 修补 pd.combine_first()

df1 = pd.DataFrame([[np.nan, 3., 5.], [-4.6, np.nan, np.nan],[np.nan, 7., np.nan]])
df2 = pd.DataFrame([[-42.6, np.nan, -8.2], [-5., 1.6, 4]],index=[1, 2])
print(df1)
print(df2)
print('------------------------------')
print(df1.combine_first(df2))
print('------------------------------')
# 根据index，df1的空值被df2替代
# 如果df2的index多于df1，则更新到df1上，比如index=['a',1]

df1.update(df2)
print(df1)
# update，直接df2覆盖df1，相同index位置

     0    1    2
0  NaN  3.0  5.0
1 -4.6  NaN  NaN
2  NaN  7.0  NaN
      0    1    2
1 -42.6  NaN -8.2
2  -5.0  1.6  4.0
------------------------------
     0    1    2
0  NaN  3.0  5.0
1 -4.6  NaN -8.2
2 -5.0  7.0  4.0
------------------------------
      0    1    2
0   NaN  3.0  5.0
1 -42.6  NaN -8.2
2  -5.0  1.6  4.0

In [26]:
'''
【课程2.18】  去重及替换

.duplicated / .replace
 
'''

'\n【课程2.18】  去重及替换\n\n.duplicated / .replace\n \n'

In [27]:
# 去重 .duplicated

s = pd.Series([1,1,1,1,2,2,2,3,4,5,5,5,5])
print(s)
print(s.duplicated())
print(s[s.duplicated() == False])
# 判断是否重复
# 通过布尔判断，得到不重复的值
print('---------------------------')

s_re = s.drop_duplicates()
print(s_re)
# drop.duplicates移除重复
# inplace参数：是否替换原值，默认False
print('-----------------------------')

df = pd.DataFrame({'key1':['a','a',3,4,5],
                  'key2':['a','a','b','b','c']})
print(df)
print(df.duplicated())
print(df['key2'].duplicated())
# Dataframe中使用duplicated

0     1
1     1
2     1
3     1
4     2
5     2
6     2
7     3
8     4
9     5
10    5
11    5
12    5
dtype: int64
0     False
1      True
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9     False
10     True
11     True
12     True
dtype: bool
0    1
4    2
7    3
8    4
9    5
dtype: int64
---------------------------
0    1
4    2
7    3
8    4
9    5
dtype: int64
-----------------------------
  key1 key2
0    a    a
1    a    a
2    3    b
3    4    b
4    5    c
0    False
1     True
2    False
3    False
4    False
dtype: bool
0    False
1     True
2    False
3     True
4    False
Name: key2, dtype: bool

In [28]:
# 替换 .replace

s = pd.Series(list('ascaazsd'))
print(s,'\n')
print(s.replace('a',np.nan))
print(s.replace(['a','e'],np.nan))
print(s.replace({'a':'hello world','s':123}))
# 可一次性替换一个值或多个值
# 可传入列表或字典

0    a
1    s
2    c
3    a
4    a
5    z
6    s
7    d
dtype: object

0    NaN
1      s
2      c
3    NaN
4    NaN
5      z
6      s
7      d
dtype: object
0    NaN
1      s
2      c
3    NaN
4    NaN
5      z
6      s
7      d
dtype: object
0    hello world
1            123
2              c
3    hello world
4    hello world
5              z
6            123
7              d
dtype: object

In [29]:
'''
【课程2.19】  数据分组

分组统计 - groupby功能

① 根据某些条件将数据拆分成组
② 对每个组独立应用函数
③ 将结果合并到一个数据结构中

Dataframe在行（axis=0）或列（axis=1）上进行分组，将一个函数应用到各个分组并产生一个新值，然后函数执行结果被合并到最终的结果对象中。

df.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs)
 
'''

'\n【课程2.19】  数据分组\n\n分组统计 - groupby功能\n\n① 根据某些条件将数据拆分成组\n② 对每个组独立应用函数\n③ 将结果合并到一个数据结构中\n\nDataframe在行（axis=0）或列（axis=1）上进行分组，将一个函数应用到各个分组并产生一个新值，然后函数执行结果被合并到最终的结果对象中。\n\ndf.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs)\n \n'

In [32]:
# 分组

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar','foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
print(df)
print('-----------------------------------')

print(df.groupby('A'),type(df.groupby('A')))
# 直接分组得到一个groupby对象，是一个中间数据，没有进行计算
print('-----------------------------------')

print(df.groupby('A').mean())           # 根据‘A’列分组，求平均值
print(df.groupby(['A','B']).mean())     # 先根据‘A’列分组，再根据‘B’列分组，求平均值
print(df.groupby('A')['D'].mean())      # 以A分组，算D的平均值
# 通过分组后的计算，得到一个新的dataframe
# 默认axis = 0，以行来分组
# 可单个或多个（[]）列分组

     A      B         C         D
0  foo    one -0.672908 -0.752583
1  bar    one  0.522146  0.734915
2  foo    two -0.057020  0.750805
3  bar  three -0.209783  0.039206
4  foo    two  0.700705  1.533218
5  bar    two  0.848127  0.240041
6  foo    one  0.330537 -0.325233
7  foo  three  1.218910  1.083782
-----------------------------------
<pandas.core.groupby.groupby.DataFrameGroupBy object at 0x0000014EA65D5BA8> <class 'pandas.core.groupby.groupby.DataFrameGroupBy'>
-----------------------------------
            C         D
A
bar  0.386830  0.338054
foo  0.304045  0.457997
                  C         D
A   B
bar one    0.522146  0.734915
    three -0.209783  0.039206
    two    0.848127  0.240041
foo one   -0.171186 -0.538908
    three  1.218910  1.083782
    two    0.321843  1.142011
A
bar    0.338054
foo    0.457997
Name: D, dtype: float64

In [64]:
# 分组 - 可迭代对象

df = pd.DataFrame({'X' : ['A', 'B', 'A', 'B'], 'Y' : [1, 4, 3, 2]})
print(df)
print(df.groupby('X'),type(df.groupby('X')))
print('---------------------------------')

print(list(df.groupby('X')))
print(list(df.groupby('X'))[0])
print('-------------------------')
for n,g in df.groupby('X'):
    print(n)
    print(g)
    print('***')
# n是组名，g是分组后的Dataframe
print('--------------------------')

print(df.groupby(['X']).get_group('A'),'\n')
print(df.groupby(['X']).get_group('B'),'\n')
# .get_group()提取分组后的组
print('----------------------------')

grouped = df.groupby('X')
print(grouped.groups)
print(grouped.groups['A'])             # 也可写：df.groupby('X').groups['A']
# .groups：将分组后的groups转为dict
# 可以字典索引方法来查看groups里的元素
print('------------------------------')

sz = grouped.size()
print(sz,type(sz))
# .size()：查看分组后的长度
print('---------------------------------')

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar','foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
grouped = df.groupby(['A','B']).groups
print(df,'\n')
print(grouped,'\n')
print(grouped[('foo','three')])
# 按照两个列进行分组

   X  Y
0  A  1
1  B  4
2  A  3
3  B  2
<pandas.core.groupby.groupby.DataFrameGroupBy object at 0x0000014EA700D0F0> <class 'pandas.core.groupby.groupby.DataFrameGroupBy'>
---------------------------------
[('A',    X  Y
0  A  1
2  A  3), ('B',    X  Y
1  B  4
3  B  2)]
('A',    X  Y
0  A  1
2  A  3)
-------------------------
A
   X  Y
0  A  1
2  A  3
***
B
   X  Y
1  B  4
3  B  2
***
--------------------------
   X  Y
0  A  1
2  A  3

   X  Y
1  B  4
3  B  2

----------------------------
{'A': Int64Index([0, 2], dtype='int64'), 'B': Int64Index([1, 3], dtype='int64')}
Int64Index([0, 2], dtype='int64')
------------------------------
X
A    2
B    2
dtype: int64 <class 'pandas.core.series.Series'>
---------------------------------
     A      B         C         D
0  foo    one -0.136624  0.956161
1  bar    one  0.656311 -0.690873
2  foo    two  0.592424 -0.332233
3  bar  three -0.710054 -0.498320
4  foo    two -0.405088 -2.348300
5  bar    two  1.855881 -2.227659
6  foo    one -1.523486  0.443551
7  foo  three -0.889573 -0.283893

{('bar', 'one'): Int64Index([1], dtype='int64'), ('bar', 'three'): Int64Index([3], dtype='int64'), ('bar', 'two'): Int64Index([5], dtype='int64'), ('foo', 'one'): Int64Index([0, 6], dtype='int64'), ('foo', 'three'): Int64Index([7], dtype='int64'), ('foo', 'two'): Int64Index([2, 4], dtype='int64')}

Int64Index([7], dtype='int64')

In [66]:
# 其他轴上的分组

df = pd.DataFrame({'data1':np.random.rand(2),
                  'data2':np.random.rand(2),
                  'key1':['a','b'],
                  'key2':['one','two']})
print(df)
print(df.dtypes)
print('------------------------------')
for n,p in df.groupby(df.dtypes, axis=1):
    print(n)
    print(p)
    print('##')
# 按照值类型分列

      data1     data2 key1 key2
0  0.030501  0.189310    a  one
1  0.460307  0.073172    b  two
data1    float64
data2    float64
key1      object
key2      object
dtype: object
------------------------------
float64
      data1     data2
0  0.030501  0.189310
1  0.460307  0.073172
##
object
  key1 key2
0    a  one
1    b  two
##

In [70]:
# 通过字典或者Series分组

df = pd.DataFrame(np.arange(16).reshape(4,4),
                  columns = ['a','b','c','d'])
print(df)
print('--------------------------------------')

mapping = {'a':'one','b':'one','c':'two','d':'two','e':'three'}
by_column = df.groupby(mapping, axis = 1)
print(by_column.sum())
print('---------------------------------------')
# mapping中，a、b列对应的为one，c、d列对应的为two，以字典来分组

s = pd.Series(mapping)
print(s,'\n')
print(s.groupby(s).count())
# s中，index中a、b对应的为one，c、d对应的为two，以Series来分组

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
--------------------------------------
   one  two
0    1    5
1    9   13
2   17   21
3   25   29
---------------------------------------
a      one
b      one
c      two
d      two
e    three
dtype: object

one      2
three    1
two      2
dtype: int64

In [71]:
# 通过函数分组

df = pd.DataFrame(np.arange(16).reshape(4,4),
                  columns = ['a','b','c','d'],
                 index = ['abc','bcd','aa','b'])
print(df,'\n')
print(df.groupby(len).sum())
# 按照字母长度分组

      a   b   c   d
abc   0   1   2   3
bcd   4   5   6   7
aa    8   9  10  11
b    12  13  14  15

    a   b   c   d
1  12  13  14  15
2   8   9  10  11
3   4   6   8  10

In [72]:
# 分组计算函数方法

s = pd.Series([1, 2, 3, 10, 20, 30], index = [1, 2, 3, 1, 2, 3])
grouped = s.groupby(level=0)  # 唯一索引用.groupby(level=0)，将同一个index的分为一组
print(grouped)
print(grouped.first(),'→ first：非NaN的第一个值\n')
print(grouped.last(),'→ last：非NaN的最后一个值\n')
print(grouped.sum(),'→ sum：非NaN的和\n')
print(grouped.mean(),'→ mean：非NaN的平均值\n')
print(grouped.median(),'→ median：非NaN的算术中位数\n')
print(grouped.count(),'→ count：非NaN的值\n')
print(grouped.min(),'→ min、max：非NaN的最小值、最大值\n')
print(grouped.std(),'→ std，var：非NaN的标准差和方差\n')
print(grouped.prod(),'→ prod：非NaN的积\n')

<pandas.core.groupby.groupby.SeriesGroupBy object at 0x0000014EA7BB2518>
1    1
2    2
3    3
dtype: int64 → first：非NaN的第一个值

1    10
2    20
3    30
dtype: int64 → last：非NaN的最后一个值

1    11
2    22
3    33
dtype: int64 → sum：非NaN的和

1     5.5
2    11.0
3    16.5
dtype: float64 → mean：非NaN的平均值

1     5.5
2    11.0
3    16.5
dtype: float64 → median：非NaN的算术中位数

1    2
2    2
3    2
dtype: int64 → count：非NaN的值

1    1
2    2
3    3
dtype: int64 → min、max：非NaN的最小值、最大值

1     6.363961
2    12.727922
3    19.091883
dtype: float64 → std，var：非NaN的标准差和方差

1    10
2    40
3    90
dtype: int64 → prod：非NaN的积

In [84]:
# 多函数计算：agg()

df = pd.DataFrame({'a':[1,1,2,2],
                  'b':np.random.rand(4),
                  'c':np.random.rand(4),
                  'd':np.random.rand(4)})
print(df,'\n')
print('---------------------------------------')

print(df.groupby('a').agg(['mean',np.sum]))
print(df.groupby('a')['b'].agg({'result1':np.mean,
                               'result2':np.sum}))
# 函数写法可以用str，或者np.方法
# 可以通过list，dict传入，当用dict时，key名为columns

   a         b         c         d
0  1  0.614741  0.080004  0.812607
1  1  0.423314  0.678966  0.896709
2  2  0.428090  0.436354  0.539945
3  2  0.292798  0.721092  0.218730

---------------------------------------
          b                   c                   d
       mean       sum      mean       sum      mean       sum
a
1  0.519027  1.038055  0.379485  0.758970  0.854658  1.709317
2  0.360444  0.720888  0.578723  1.157446  0.379338  0.758676
    result1   result2
a
1  0.519027  1.038055
2  0.360444  0.720888

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  if sys.path[0] == '':

In [ ]:
'''
【课程2.20】  分组转换及一般性“拆分-应用-合并”

transform / apply
 
'''

In [98]:
# 数据分组转换,transform

df = pd.DataFrame({'data1':np.random.rand(5),
                  'data2':np.random.rand(5),
                  'key1':list('aabba'),
                  'key2':['one','two','one','two','one']})
k_mean = df.groupby('key1').mean()
print(df,'\n')
print(k_mean)
print('---------------------------------')
print(pd.merge(df,k_mean,left_on='key1',right_index=True).add_prefix('mean_'))
# 通过分组、合并，得到一个包含均值的Dataframe
print('---------------------------------\n')

print(df.groupby('key2').mean(),'\n')
print(df.groupby('key2').transform(np.mean))
# data1、data2每个位置元素取对应分组列的均值
# 字符串不能进行计算

      data1     data2 key1 key2
0  0.554341  0.339380    a  one
1  0.985333  0.762543    a  two
2  0.548791  0.050229    b  one
3  0.652649  0.375120    b  two
4  0.622815  0.350406    a  one

        data1     data2
key1
a     0.72083  0.484110
b     0.60072  0.212675
---------------------------------
   mean_data1_x  mean_data2_x mean_key1 mean_key2  mean_data1_y  mean_data2_y
0      0.554341      0.339380         a       one       0.72083      0.484110
1      0.985333      0.762543         a       two       0.72083      0.484110
4      0.622815      0.350406         a       one       0.72083      0.484110
2      0.548791      0.050229         b       one       0.60072      0.212675
3      0.652649      0.375120         b       two       0.60072      0.212675
---------------------------------

         data1     data2
key2
one   0.575316  0.246672
two   0.818991  0.568831

      data1     data2
0  0.575316  0.246672
1  0.818991  0.568831
2  0.575316  0.246672
3  0.818991  0.568831
4  0.575316  0.246672

In [102]:
# 一般化Groupby方法：apply

df = pd.DataFrame({'data1':np.random.rand(5),
                  'data2':np.random.rand(5),
                  'key1':list('aabba'),
                  'key2':['one','two','one','two','one']})

print(df.groupby('key1').apply(lambda x: x.describe()))
# apply直接运行其中的函数
# 这里为匿名函数，直接描述分组后的统计量

def f_df1(d,n):
    return(d.sort_index()[:n])
def f_df2(d,k1):
    return(d[k1])
print(df.groupby('key1').apply(f_df1,2),'\n')
print(df.groupby('key1').apply(f_df2,'data2'))
print(type(df.groupby('key1').apply(f_df2,'data2')))
# f_df1函数：返回排序后的前n行数据
# f_df2函数：返回分组后表的k1列，结果为Series，层次化索引
# 直接运行f_df函数
# 参数直接写在后面，也可以为.apply(f_df,n = 2))

               data1     data2
key1
a    count  3.000000  3.000000
     mean   0.395563  0.300365
     std    0.497688  0.142045
     min    0.031822  0.149771
     25%    0.111974  0.234574
     50%    0.192125  0.319377
     75%    0.577434  0.375662
     max    0.962742  0.431947
b    count  2.000000  2.000000
     mean   0.559486  0.660842
     std    0.322445  0.088325
     min    0.331483  0.598386
     25%    0.445484  0.629614
     50%    0.559486  0.660842
     75%    0.673487  0.692069
     max    0.787489  0.723297
           data1     data2 key1 key2
key1
a    0  0.962742  0.149771    a  one
     1  0.031822  0.431947    a  two
b    2  0.787489  0.598386    b  one
     3  0.331483  0.723297    b  two

key1
a     0    0.149771
      1    0.431947
      4    0.319377
b     2    0.598386
      3    0.723297
Name: data2, dtype: float64
<class 'pandas.core.series.Series'>

In [103]:
'''
【课程2.21】  透视表及交叉表

类似excel数据透视 - pivot table / crosstab
 
'''

'\n【课程2.21】  透视表及交叉表\n\n类似excel数据透视 - pivot table / crosstab\n \n'

In [107]:
# 透视表：pivot_table
# pd.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')

date = ['2017-5-1','2017-5-2','2017-5-3']*3
rng = pd.to_datetime(date)
df = pd.DataFrame({'date':rng,
                   'key':list('abcdabcda'),
                  'values':np.random.rand(9)*10})
print(df)
print('------------------------------------------')

print(pd.pivot_table(df, values = 'values', index = 'date', columns = 'key', aggfunc=np.sum))  # 也可以写 aggfunc='sum'
print('------------------------------------------')
# data：DataFrame对象
# values：要聚合的列或列的列表
# index：数据透视表的index，从原数据的列中筛选
# columns：数据透视表的columns，从原数据的列中筛选
# aggfunc：用于聚合的函数，默认为numpy.mean，支持numpy计算方法

print(pd.pivot_table(df, values = 'values', index = ['date','key']))
print('------------------------------------------')
# 这里就分别以date、key共同做数据透视，值为values：统计不同（date，key）情况下values的平均值
# aggfunc=len(或者count)：计数

        date key    values
0 2017-05-01   a  7.775912
1 2017-05-02   b  2.533939
2 2017-05-03   c  7.761361
3 2017-05-01   d  0.969603
4 2017-05-02   a  6.799217
5 2017-05-03   b  7.226215
6 2017-05-01   c  9.553374
7 2017-05-02   d  8.555208
8 2017-05-03   a  0.233832
------------------------------------------
key                a         b         c         d
date
2017-05-01  7.775912       NaN  9.553374  0.969603
2017-05-02  6.799217  2.533939       NaN  8.555208
2017-05-03  0.233832  7.226215  7.761361       NaN
------------------------------------------
                  values
date       key
2017-05-01 a    7.775912
           c    9.553374
           d    0.969603
2017-05-02 a    6.799217
           b    2.533939
           d    8.555208
2017-05-03 a    0.233832
           b    7.226215
           c    7.761361
------------------------------------------

In [112]:
# 交叉表：crosstab
# 默认情况下，crosstab计算因子的频率表，比如用于str的数据透视分析
# pd.crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins=False, dropna=True, normalize=False)

df = pd.DataFrame({'A': [1, 2, 2, 2, 2],
                   'B': [3, 3, 4, 4, 4],
                   'C': [1, 1, np.nan, 1, 1]})
print(df)
print('----------------------------------------------')

print(pd.crosstab(df['A'],df['B']))
print('----------------------------------------------')
# 如果crosstab只接收两个Series，它将提供一个频率表。
# 用A的唯一值，统计B唯一值的出现次数

print(pd.crosstab(df['A'],df['B'],normalize=True))
print('----------------------------------------------')
# normalize：默认False，将所有值除以值的总和进行归一化 → 为True时候显示百分比

print(pd.crosstab(df['A'],df['B'],values=df['C'],aggfunc=np.sum))
print('----------------------------------------------')
# values：可选，根据因子聚合的值数组
# aggfunc：可选，如果未传递values数组，则计算频率表，如果传递数组，则按照指定计算
# 这里相当于以A和B界定分组，计算出每组中第三个系列C的值

print(pd.crosstab(df['A'],df['B'],values=df['C'],aggfunc=np.sum, margins=True))
print('-----------------------------------------------')
# margins：布尔值，默认值False，添加行/列边距（小计）

   A  B    C
0  1  3  1.0
1  2  3  1.0
2  2  4  NaN
3  2  4  1.0
4  2  4  1.0
----------------------------------------------
B  3  4
A
1  1  0
2  1  3
----------------------------------------------
B    3    4
A
1  0.2  0.0
2  0.2  0.6
----------------------------------------------
B    3    4
A
1  1.0  NaN
2  1.0  2.0
----------------------------------------------
B      3    4  All
A
1    1.0  NaN  1.0
2    1.0  2.0  3.0
All  2.0  2.0  4.0
-----------------------------------------------

In [ ]:
'''
【课程2.22】  数据读取

核心：read_table, read_csv, read_excel
 
'''

In [113]:
# 读取普通分隔数据：read_table
# 可以读取txt，csv

data1 = pd.read_table('data1.txt',delimiter = ',',header = 0,index_col = 1)
print(data1)
# delimiter：用于拆分的字符，也可以用sep：sep = ','
# header：用做列名的序号，默认为0（第一行）
# index_col：指定某列为行索引，否则自动索引0, 1, .....

# read_table主要用于读取简单的数据，txt/csv

     va1  va3  va4
va2
2      1    3    4
3      2    4    5
4      3    5    6
5      4    6    7

In [123]:
# 读取csv数据：read_csv
# 先熟悉一下excel怎么导出csv

data2 = pd.read_csv('data2.csv',engine='python')
print(data2.head())
print(data2.tail())

# engine：使用的分析引擎。可以选择C或者是python。C引擎快但是Python引擎功能更加完备。
# encoding：指定字符集类型，即编码，通常指定为'utf-8'

# 大多数情况先将excel导出csv，再读取

   省级政区代码 省级政区名称  地市级政区代码 地市级政区名称    年份 党委书记姓名  出生年份  出生月份  籍贯省份代码 籍贯省份名称  \
0  130000    河北省   130100    石家庄市  2000    陈来立   NaN   NaN     NaN    NaN
1  130000    河北省   130100    石家庄市  2001    吴振华   NaN   NaN     NaN    NaN
2  130000    河北省   130100    石家庄市  2002    吴振华   NaN   NaN     NaN    NaN
3  130000    河北省   130100    石家庄市  2003    吴振华   NaN   NaN     NaN    NaN
4  130000    河北省   130100    石家庄市  2004    吴振华   NaN   NaN     NaN    NaN

   ...    民族  教育 是否是党校教育（是=1，否=0） 专业：人文 专业：社科  专业：理工  专业：农科  专业：医科  入党年份  工作年份
0  ...   NaN  硕士              1.0   NaN   NaN    NaN    NaN    NaN   NaN   NaN
1  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN
2  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN
3  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN
4  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN

[5 rows x 23 columns]
      省级政区代码    省级政区名称  地市级政区代码 地市级政区名称    年份 党委书记姓名  出生年份  出生月份  籍贯省份代码  \
3658  650000  新疆维吾尔自治区   654300   阿勒泰地区  2006    NaN   NaN   NaN     NaN
3659  650000  新疆维吾尔自治区   654300   阿勒泰地区  2007    NaN   NaN   NaN     NaN
3660  650000  新疆维吾尔自治区   654300   阿勒泰地区  2008    NaN   NaN   NaN     NaN
3661  650000  新疆维吾尔自治区   654300   阿勒泰地区  2009    NaN   NaN   NaN     NaN
3662  650000  新疆维吾尔自治区   654300   阿勒泰地区  2010    NaN   NaN   NaN     NaN

     籍贯省份名称  ...    民族   教育 是否是党校教育（是=1，否=0） 专业：人文 专业：社科  专业：理工  专业：农科  专业：医科  \
3658    NaN  ...   NaN  NaN              NaN   NaN   NaN    NaN    NaN    NaN
3659    NaN  ...   NaN  NaN              NaN   NaN   NaN    NaN    NaN    NaN
3660    NaN  ...   NaN  NaN              NaN   NaN   NaN    NaN    NaN    NaN
3661    NaN  ...   NaN  NaN              NaN   NaN   NaN    NaN    NaN    NaN
3662    NaN  ...   NaN  NaN              NaN   NaN   NaN    NaN    NaN    NaN

      入党年份  工作年份
3658   NaN   NaN
3659   NaN   NaN
3660   NaN   NaN
3661   NaN   NaN
3662   NaN   NaN

[5 rows x 23 columns]

In [131]:
# 读取excel数据：read_excel

data3 = pd.read_excel('地市级党委书记数据库（2000-10）.xlsx',sheetname='中国人民共和国地市级党委书记数据库（2000-10）',header=0)
print(data3.head(),type(data3))
# io ：文件路径。
# sheetname：返回多表使用sheetname=[0,1],若sheetname=None是返回全表 → ① int/string 返回的是dataframe ②而none和list返回的是dict
# header：指定列名行，默认0，即取第一行
# index_col：指定列为索引列，也可以使用u”strings”

   省级政区代码 省级政区名称  地市级政区代码 地市级政区名称    年份 党委书记姓名  出生年份  出生月份  籍贯省份代码 籍贯省份名称  \
0  130000    河北省   130100    石家庄市  2000    陈来立   NaN   NaN     NaN    NaN
1  130000    河北省   130100    石家庄市  2001    吴振华   NaN   NaN     NaN    NaN
2  130000    河北省   130100    石家庄市  2002    吴振华   NaN   NaN     NaN    NaN
3  130000    河北省   130100    石家庄市  2003    吴振华   NaN   NaN     NaN    NaN
4  130000    河北省   130100    石家庄市  2004    吴振华   NaN   NaN     NaN    NaN

   ...    民族  教育 是否是党校教育（是=1，否=0） 专业：人文 专业：社科  专业：理工  专业：农科  专业：医科  入党年份  工作年份
0  ...   NaN  硕士              1.0   NaN   NaN    NaN    NaN    NaN   NaN   NaN
1  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN
2  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN
3  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN
4  ...   NaN  本科              0.0   0.0   0.0    1.0    0.0    0.0   NaN   NaN

[5 rows x 23 columns] <class 'pandas.core.frame.DataFrame'>